# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c82b07192ab4e84cd8a994d041a6f70ff799acb54d34d5dafa24611454ecb8b52a225649a6e7f951f114e493480ab47b4e4dba442790716da500ed723287204b

test:
  secret_key_base: df7910a34bd8c271a47ccc2c25964dbba948d0c06a279c54ef7038a72fdab3a8b9298ce7add85b9da1097460d8827107baae18bc01198297b43c07165243fdb8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
